### ISSUE TITLE
Compairing RTTM file

### ISSUE THREAD

**Issue by aishwaryjoshi31** [idiap/IBDiarization#10]
Hi,

I have successfully diarized a meeting from AMI corpus. I want to check the diarization error that  my output contains. How do I check? I checked AMI corpus but did not find rttm file there to compare with rttm file that is generated as a result of diarization. Can anybody help?

**Comment by mrsrikanth** [comment]
Hello,

You will have to create your own RTTM files from groundtruth
available in the AMI dataset. A sample RTTM file is already available
in the package.

Srikanth

**Comment by aishwaryjoshi31** [comment]
Hi @mrsrikanth Can you please elaborate more. I did not get you.

**Comment by mrsrikanth** [comment]
The AMI dataset has [manual annotations](http://groups.inf.ed.ac.uk/ami/AMICorpusAnnotations/ami_public_manual_1.6.1.zip) that has
segment-level information (in XML format)  for each speaker for each recording.
You can easily convert this to RTTM format to use as groundtruth for
diarization.

Srikanth

**Comment by aishwaryjoshi31** [comment]
Okay, So there is "segment" folder which contains segment level information in xml format but doesn't contain which speaker spoke in a particular segment .Isn't it?

**Comment by aishwaryjoshi31** [comment]
The segment folder contains information about each recording only , I did not see speaker information in that folder so here is image of one of the xml file in segment folder. Can you point it out where is speaker information?
![screenshot from 2017-03-30 15-35-38](https://cloud.githubusercontent.com/assets/20510586/24499333/ef90fcb2-155e-11e7-857e-b51e613d3879.png)

**Comment by mrsrikanth** [comment]
The file name that you have attached is IS1000a.A.segments.xml.
The 'A' in the suffix is the speaker name for that file. You will also find
segment information for speakers B, C and D. To translate A, B, C and D
to global-level speaker identities, you can check .corpusResources/meetings.xml.

**Comment by aishwaryjoshi31** [comment]
Thanks @mrsrikanth  for your help. Few last things : Are there any overlapping between the speakers, for eg speaker s1 is speaking from let say t=1 to t=5 and speaker s2 speaking from t=3 to t=7. So are there any such cases like this one?

**Comment by cunnie** [comment]
@aishwaryjoshi31 You may find a [script](https://github.com/cunnie/bin/blob/26eecbc292fc9066be0554447fe69afcafd2295c/nite_xml_to_rttm.py) I wrote useful for converting the AMI Corpus's XML files to RTTM format. Typical invocation:

```
nite_xml_to_rttm.py ~/Downloads/ami_public_manual_1.6.2/words/ES2008a.*.words.xml |
    sort -n -k 4 > /tmp/ES2008a.rttm
```
