### ISSUE TITLE
TDOA feature extraction

### ISSUE THREAD

**Issue by aishwaryjoshi31** [idiap/IBDiarization#12]
Is there any tool to obtain TDOA feature ? Please help.

**Comment by mrsrikanth** [comment]
Hello,

Please see https://github.com/xanguera/BeamformIt

Srikanth

**Comment by aishwaryjoshi31** [comment]
What is diarization error for AMI corpus data set with and without tdoa feature, please let me know the paper where experiment is actually performed on AMI corpus meeting data.

**Comment by aishwaryjoshi31** [comment]
Hey @mrsrikanth  , I got 3 files ".del" ".del2" and ".weat" as the output from beamforit  but how to generate tdoa feature file using these files? please let me know.

**Comment by mrsrikanth** [comment]
Please refer to the README of the package. It should be NIST_20051024-0930.del.

**Comment by aishwaryjoshi31** [comment]
What is diarization error for AMI corpus data set with and without tdoa feature, also please let me know the paper where experiment is actually performed on AMI corpus meeting data.

**Comment by mrsrikanth** [comment]
You can refer to 

Yella, Sree Harsha, et al. "Phoneme background model for information bottleneck based speaker diarization." Interspeech. No. EPFL-CONF-203864. 2014.
