### ISSUE TITLE
Toolkit Crash

### ISSUE THREAD

**Issue by aishwaryjoshi31** [idiap/IBDiarization#13]
Toolkit crashed when I ran the experiment by including tdoa feature for diarization. Here is the snapshot of actual error.
![screenshot from 2017-04-24 17-14-04](https://cloud.githubusercontent.com/assets/20510586/25335073/0ca2f972-290f-11e7-84bd-d7861d21b128.png)
Content of ".out file"
 AIB diarization started at 414731 

 MFCC:   data/mfcc/IS1005a.feat  weight MFCC  0.8 
 TDOA:   data/tdoa/IS1005a.weat  weight TDOA 0.2 

 Maximum Segment Duration 250 

 AIB is running with the following parameters

 Maximum number of clusters possible: 		10
 Normalized Mutual Information threshold: 		0.5
 Beta value: 		10
 Number of threads: 		1

 Reading and Processing the scp file 
number of segments inside = 1716
Number of vectors = 39897
Feat file data/mfcc/IS1005a.feat of type 0
Reading feature file data/mfcc/IS1005a.feat
frame dim: 12
num_vec = 39897
Attempting memory allocation.
Memory successully allocated.
Reading file ... 
all segments read 
Number of segments in the file = 1722
num_vec = 39897  idx = 0
Feat file data/tdoa/IS1005a.weat of type 2
Reading feature file data/tdoa/IS1005a.weat
frame dim: 3148
num_vec = 39897
Attempting memory allocation.

**Comment by mrsrikanth** [comment]
Hello, 

There seems to be an issue with the feature file  data/tdoa/IS1005a.weat.
Please make sure it is in the right format. I suspect type 2 is not a valid
format for the weat features.

Thanks,
Srikanth

**Comment by aishwaryjoshi31** [comment]
Yes I changed the file from ".weat" to ".del" but still getting same error. I think the problem is because of memory allocation. If you can see the code for extract_feature.cpp, there it is reading HTK header for ".del" file and dimension of each frame comes out to be very large and allocating that much amount of memory for each frame is not feasible. So I suspect that something is wrong with frame_dimension or the format of ".del" file. I am attaching log file and the code snippet to get the clear picture of scenario. 
![screenshot from 2017-04-27 16-32-16](https://cloud.githubusercontent.com/assets/20510586/25480034/a3e4516c-2b64-11e7-8fb4-c68c2a1d65ff.png)

**Comment by mrsrikanth** [comment]
Hello,

Is your feature dimensionality 3083? There are two possibilities  here:

1. Feature file is not in the right format. Please see the sample TDOA features in the toolkit.
2. If this is indeed the feature you want to use, you do not have enough memory in your machine to  run diarization with these features.

Srikanth

**Comment by aishwaryjoshi31** [comment]
No size of feature dimension is only 8 but file interpretation is wrong. I exactly did what you said I first tried to check sample tdoa feature file but its content can't be read as garbage values are coming. I think the tdoa feature file in data folder is generated by some other toolkit rather than by BeamformIt).

**Comment by mrsrikanth** [comment]
The same toolkit was used. Are you sure that the .del file is in HTK format?

**Comment by aishwaryjoshi31** [comment]
I don't think that BeamformIt tool generate in HTK format. Here is the content of file. There is no header nothing.
![image](https://cloud.githubusercontent.com/assets/20510586/25496015/0f8fce7c-2b9d-11e7-95b1-2646fd3ac139.png)

**Comment by mrsrikanth** [comment]
Yes, that is expected. You need to convert this file to htk format. 
You need to choose the appropriate columns from this file to form the TDOA features.
I suggest you to refer to their documentation.
