### ISSUE TITLE
Toolkit for TDOA feature

### ISSUE THREAD

**Issue by glynpu** [idiap/IBDiarization#14]
Hi Srikanth,

Could I know which toolkit do you use to extract TDOA feature?

I have installed a Toolkit called BeamformIt implemented by Xavier Anguera . But the output TDOA is in plain text format, which is in different format with the TDOA example you provided. Actually, I have no idea what format it is in.

Best wishes, 
Liyong Guo

**Comment by mrsrikanth** [comment]
Hi,

You need to convert the TDOA features to HTK format just
like the MFCC files.

Thanks,
Srikanth

**Comment by glynpu** [comment]
Hi Srikanth,

Now there is a small problem about the conversion.

Could you give me a clue how to convert the plain text TDOA to HTK format?

My idea is using HCopy command, but I don't know the exact process.

Now the TDOA is in the the following format:

`0 -> 0 1.000000  0 1.000000  0 1.000000  -2 0.132788  0 1.000000  -2 0.157925  0 1.000000  0 1.000000 
250 -> 0 0.081363  0 0.088067  -5 0.125728  -3 0.133382  0 1.000000  -2 0.158627  0 0.091988  0 0.089718 
500 -> 0 0.065306  0 0.077321  -5 0.111814  -3 0.132347  0 1.000000  -2 0.162307  0 0.093127  0 0.102211 
750 -> 0 0.066661  0 0.068743  -5 0.100992  -2 0.120905  0 1.000000  -2 0.163557  0 0.093942  0 0.090335 
1000 -> 0 0.064726  7 0.107366  -5 0.117871  -3 0.130984  0 1.000000  -2 0.180463  0 0.090841  0 0.081424 
`

Best wishes,
Liyong Guo

**Comment by glynpu** [comment]
Aha, the writehtk function in Voicebox toolkit meets the requirement.
