### ISSUE TITLE
Error while compilation

### ISSUE THREAD

**Issue by brijmohan** [idiap/IBDiarization#2]
`[  6%] Building CXX object CMakeFiles/diarizeme.dir/home/brij/Documents/tools/voicefox/IBDiarization/src/diarization/src/diarizeme.cpp.o

In file included from /home/brij/Documents/tools/voicefox/IBDiarization/src/diarization/cmake/../../aibfeat/include/gmm.h:23:0,

                 from /home/brij/Documents/tools/voicefox/IBDiarization/src/diarization/cmake/../../aibfeat/include/hmmreadwrite.h:23,

                 from /home/brij/Documents/tools/voicefox/IBDiarization/src/diarization/src/diarizeme.cpp:39:
/home/brij/Documents/tools/voicefox/IBDiarization/src/diarization/cmake/../../utils/include

/global.h:39:11: error: expected identifier before numeric constant
 #define P 2 //variable to decide the initialization
           ^

/home/brij/Documents/tools/voicefox/IBDiarization/src/diarization/cmake/../../utils/include/global.h:39:11: error: expected ‘>’ before numeric constant
In file included from /usr/include/boost/smart_ptr/make_shared_array.hpp:12:0,
                 from /usr/include/boost/smart_ptr/make_shared.hpp:18,
                 from /usr/include/boost/make_shared.hpp:15,
                 from /usr/include/boost/smart_ptr.hpp:28,
                 from /home/brij/Documents/tools/voicefox/IBDiarization/src/diarization/cmake/../../utils/include/tools.h:38,
                 from /home/brij/Documents/tools/voicefox/IBDiarization/src/diarization/cmake/../../aIB/include/aIB.h:34,
                 from /home/brij/Documents/tools/voicefox/IBDiarization/src/diarization/src/diarizeme.cpp:45:
/usr/include/boost/smart_ptr/detail/array_count_impl.hpp:18:59: error: ‘A’ was not declared in this scope
         class sp_counted_impl_pda<P, ms_in_allocator_tag, A>
                                                           ^
/usr/include/boost/smart_ptr/detail/array_count_impl.hpp:18:60: error: type/value mismatch at argument 1 in template parameter list for ‘template<class P, class D, class A> class boost::detail::sp_counted_impl_pda’
         class sp_counted_impl_pda<P, ms_in_allocator_tag, A>
                                                            ^
/usr/include/boost/smart_ptr/detail/array_count_impl.hpp:18:60: note:   expected a type, got ‘2’
/usr/include/boost/smart_ptr/detail/array_count_impl.hpp:18:60: error: template argument 3 is invalid
CMakeFiles/diarizeme.dir/build.make:62: recipe for target 'CMakeFiles/diarizeme.dir/home/brij/Documents/tools/voicefox/IBDiarization/src/diarization/src/diarizeme.cpp.o' failed
make[2]: *** [CMakeFiles/diarizeme.dir/home/brij/Documents/tools/voicefox/IBDiarization/src/diarization/src/diarizeme.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/diarizeme.dir/all' failed
make[1]: *** [CMakeFiles/diarizeme.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`

Hi, I am trying to compile the package using g++ 5.4.0 in Ubuntu 16.04. I have installed Boost library.

Kindly suggest how to fix this error. Thanks,

**Comment by mrsrikanth** [comment]
Hello,

There seems to be a name collision with the latest boost libraries.
I have modified the code to handle this. You should now be able to
compile the latest code (after pulling the change) in Ubuntu 16.04.

Thanks,
Srikanth

**Comment by brijmohan** [comment]
Hi Srikanth,

The code compiles after the removal of macro. Thanks for the help.
