### ISSUE TITLE
Is there a way not to save the files *.post.0 and *.post.all in the results dir?

### ISSUE THREAD

**Issue by akomaty** [idiap/IBDiarization#5]
Files like *.post.0 and *.post.all are huge in size, so is there a way to prevent the code from saving them?
Or I should create a bash script to delete them once they appear?

**Comment by mrsrikanth** [comment]
Hello,

I would recommend deleting them only after the entire process for the audio file is done. 
The KL-HMM realignment uses the *.post.all file and requires the entire
file to train models. 

Srikanth

**Comment by akomaty** [comment]
So far the script processsed 2 files, if you look at the results directory below you can see how BIG these files *.post0 and *.post.all are. So in the following example I can delete EN2001a.post.0 and EN2001a.post.all. Then, once EN2001b.rttm appears, I can delete EN2001b.post.0 and EN2001b.post.all?
```
-rw-r--r-- 1 akomaty idiap        761 Jan 26 11:55 EN2001a.clust.out
-rw-r--r-- 1 akomaty idiap     283765 Jan 26 11:52 EN2001a.feat.0
-rw-r--r-- 1 akomaty idiap     283765 Jan 26 11:54 EN2001a.feat.all
-rw-r--r-- 1 akomaty idiap     442202 Jan 26 11:51 EN2001a.hmm.0
-rw-r--r-- 1 akomaty idiap       3319 Jan 26 11:55 EN2001a.out
-rw-r--r-- 1 akomaty idiap  789636108 Jan 26 11:52 EN2001a.post.0
-rw-r--r-- 1 akomaty idiap  789636108 Jan 26 11:54 EN2001a.post.all
-rw-r--r-- 1 akomaty idiap      21232 Jan 26 11:55 EN2001a.rttm
-rw-r--r-- 1 akomaty idiap      18136 Jan 26 11:51 EN2001a.scp
-rw-r--r-- 1 akomaty idiap    4437591 Jan 26 11:59 EN2001b.feat.0
-rw-r--r-- 1 akomaty idiap    4437591 Jan 26 12:04 EN2001b.feat.all
-rw-r--r-- 1 akomaty idiap    1755176 Jan 26 11:55 EN2001b.hmm.0
-rw-r--r-- 1 akomaty idiap        852 Jan 26 12:04 EN2001b.out
-rw-r--r-- 1 akomaty idiap 2055933784 Jan 26 11:59 EN2001b.post.0
-rw-r--r-- 1 akomaty idiap 2055933784 Jan 26 12:04 EN2001b.post.all
-rw-r--r-- 1 akomaty idiap      71263 Jan 26 11:55 EN2001b.scp
```

**Comment by mrsrikanth** [comment]
You can delete it once diarzeme finishes, if that is what you are asking.

**Comment by akomaty** [comment]
I'll be more precise in describing my question:
Let's say I have 2 feature files: 1.fea, 2.fea

1. I launched the script: `bash scripts/run.diarizeme.qsub.sh FILE_LIST /SCP/ results.dir AMI_test`
2. In the results.dir directory, files will start to appear, first the files corresponding to 1.fea:
```
1.clust.out       1.out              1.scp       
1.feat.0          1.post.0    
1.feat.all        1.post.all  
1.hmm.0           1.rttm     
```
3. Once the first file (1.fea) is processed, then files for the second feature (2.fea) will start to appear. My question is:
**When the processing of the second feature starts (2.fea), can I delete the unwanted files corresponding to the first feature (1.post.0 and 1.post.all)?**

**Comment by mrsrikanth** [comment]
Yes, you can delete them. It wont affect the processing of 2.fea.
