### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by aishwaryjoshi31** [idiap/IBDiarization#7]
Please help me out on this. The scp file is generated by Bob and the feature file is obtained using HTK. Now I have both scp and fea files, so I ran the diarization command (bash run.diarizeme.sh..... command) but I am getting segmentation fault and I am unable to determine the cause for segmentation fault. Can  anyone tell me ,what could be the possible problems that caused segmentation fault.

**Comment by akomaty** [comment]
Hi @aishwaryjoshi31,

Please provide detailed info about your experiment and the command you're trying to run and the output of the log file in the results directory, i.e FILENAME.out

**Comment by aishwaryjoshi31** [comment]
![image](https://cloud.githubusercontent.com/assets/20510586/22881219/927062c8-f20b-11e6-819b-5d1f5339fbfb.png)

**Comment by aishwaryjoshi31** [comment]
![image](https://cloud.githubusercontent.com/assets/20510586/22881234/9ed13db2-f20b-11e6-952a-9a3573c73e47.png)
![image](https://cloud.githubusercontent.com/assets/20510586/22881307/df24800e-f20b-11e6-8ced-13b4405ffc5f.png)

Image 2 is content of .out file

**Comment by akomaty** [comment]
By just looking at the file I can see that the problem probably comed from the .scp file because the Number of segments in the file is zero.
Please share with us the .scp file, or at least part of it, say first couple of lines.

**Comment by aishwaryjoshi31** [comment]
Here is snapshot of scp file.
![image](https://cloud.githubusercontent.com/assets/20510586/22881805/28f77aae-f20e-11e6-91a8-3b379718624c.png)

**Comment by akomaty** [comment]
Please pay attention to the following .scp format:
segment_name=filename[start_frame,end_frame]
In your case: ../ami_161_201=../ami.scp[161,201]
NOT: ../ami_161_201=../ami.scp[161_201]
You did put an underscore instead of a comma between the brackets.

**Comment by aishwaryjoshi31** [comment]
Thanks a lot. I didn't pay attention there

**Comment by aishwaryjoshi31** [comment]
I am sorry to trouble you again and again but as I am new to this toolkit, so I am facing issues in using it.
![image](https://cloud.githubusercontent.com/assets/20510586/22882442/1714a598-f211-11e6-92ce-03984b5f274f.png)

**Comment by akomaty** [comment]
in this case check for possible problems in the corresponding feature. This problem may be caused by the VAD, which VAD are you using?

**Comment by aishwaryjoshi31** [comment]
I am using Energy_2Gauss for VAD.

**Comment by akomaty** [comment]
I don't know what file in the AMI dataset are you using, but I suggest for you to check for NAN values in the file itself.
If so, you have two solutions, either you have to discard these values or you can use another file.

In fact, I was rethinking your problem, and it cannot be caused by the VAD because the output of Bob's VAD is a vector of labels, you'll get as many labels as frames, the labels corresponding to one are the ones considered as speech and the ones corresponding to zero are considered silence. So Bob does not apply these label to your original signal.
In order to localize the problem you have to:

1. Check the raw signal itself and look for NAN or INF values.
2. if there's no problem with the raw signal, check the feature file.

**Comment by aishwaryjoshi31** [comment]
What is the window/frame size that bob uses. I think the frame length defined in bob to get VAD is different than the frame length used in htk to generate features and may be because of that error is occuring.

**Comment by akomaty** [comment]
You can check the source code for the preprocessor in:
```
 bob.bio.spear /bob/bio/spear/preprocessor/Energy_2Gauss.py
```
However, if you don't want to go through the source code, here are the default values used by Energy_2Gauss:
```
max_iterations = 10,        # 10 iterations for the
convergence_threshold = 0.0005,
variance_threshold = 0.0005,
win_length_ms = 20.,        # 20 ms
win_shift_ms = 10.,           # 10 ms
smoothing_window = 10, # 10 frames (i.e. 100 ms)
```

**Comment by aishwaryjoshi31** [comment]
Here is the setting of parameters for HTK. Can you please let me know ,are this values accurate for the AMI corpus data. Earlier window size was set to 25000, I changed to 20000 so now the NaN value got shifted from idx=1 to idx=9.
![image](https://cloud.githubusercontent.com/assets/20510586/22926350/3cf28a7a-f2d2-11e6-8bd7-d7948ca5ccb8.png)

**Comment by akomaty** [comment]
I don't know about HTK toolkit, I use Bob to extract features and then I put them in HTK format. So I can't help you if the problem comes from the HTK toolkit.
But usually, for MFCC features, we use a window shift of 10 ms and a window size of 20 ms.
But as a told before, the problem could be from the raw audio file itself, AMI has more than one corrupted files, so please refer to the AMI documentation [http://groups.inf.ed.ac.uk/ami/corpus/dataproblems.shtml] for more details.

**Comment by aishwaryjoshi31** [comment]
How did you put the features in HTK format.

**Comment by akomaty** [comment]
Bob will give you features in hdf5 format, they'll be stored in a directory called /extracted.
your job is to convert these hdf5 files to HTK format. Here's a code that can do it for you, modify it to fit your needs:

```
import sys
import numpy as np
import bob.io.base
import re
import os
import bob.core
logger = bob.core.log.setup("bob.db.ami")
# HTK parameter kinds
parmKind = {
    "LPC":       1,
    "LPREFC":    2,
    "LPCEPSTRA": 3,
    "MFCC":      6,
    "FBANK":     7,
    "MELSPEC":   8,
    "USER":      9,
    "PLP":      11,
    "E":   0000100,
    "N":   0000200,
    "D":   0000400,
    "A":   0001000,
    "Z":   0004000,
    "0":   0020000,
    "T":   0100000
}

# Sink to HTK file
from struct import pack, unpack
from os import makedirs
from os.path import dirname, exists

def HTKSink(fileName, a, period=0.01, kind="USER", native=False):
    if (a.ndim != 2):
        print "Dimension must be 2"
        exit(1)

    htkKind = 0
    for k in kind.split('_'):
        htkKind |= parmKind[k]
    htkPeriod = period * 1e7 + 0.5
    fmt = '>iihh'
    if native:
        fmt = 'iihh'
    header = pack(fmt, a.shape[0], htkPeriod, a.shape[1]*4, htkKind)
    print a.shape[0], htkPeriod, a.shape[1]*4, htkKind

    dir = dirname(fileName)
    if dir and not exists(dir):
        makedirs(dir)
    with open(fileName, 'wb') as f:
        # Need to create a new array here of type float32 ('f') such
        # that it is written as 4 bytes.  Casting doesn't seem to
        # work.
        f.write(header)
        v = np.array(a, dtype='f')
        if ((not native) and (sys.byteorder == 'little')):
            v = v.byteswap()
        v.tofile(f)

def main(HenergPATH, tempPath):
        fh = bob.io.base.HDF5File(DIRECTORY_TO_YOUR_FEATURE.hdf5)
        mfcc = fh.read(YOUR_MFCC)
        print 'Converting HDF5 file to HTK format ...\n'
        HTKSink(YOUR_FILENAME.feat, mfcc, period=0.01, kind='MFCC', native=False)   
        del fh 
```

**Comment by aishwaryjoshi31** [comment]
I think the problem is with the file. Do you have any file for which it is giving correct output, if yes can you share that with me?

**Comment by akomaty** [comment]
You can find a feature file in:
``` data/mfcc/AMI_20050204-1206.fea ```

The corresponding .scp file is in:
```data/scp/AMI_20050204-1206.scp```

And to evaluate your results, the rttm file is in:
```data/rttm/AMI_20050204-1206.rttm```

**Comment by aishwaryjoshi31** [comment]
For that feature and scp file it is working correctly. But I wanted to be assured that the problem is just because of wav file and not because of anything else.

**Comment by akomaty** [comment]
well just try another wav file to see, my features cannot be shared because of their size (around 100 MB each).

**Comment by aishwaryjoshi31** [comment]
Hey Do you know any open source dataset for broadcast data domain or meeting data domain?

**Comment by mrsrikanth** [comment]
Hello,

AMI (referenced in this thread multiple times) is an open source dataset for meetings.

We seem to have digressed a lot from the original thread. Unless
you have any further queries about the toolkit, I shall close this thread.

Thank you,
Srikanth

**Comment by aishwaryjoshi31** [comment]
Yes I understand , I myself is closing this thread. Thanks @akomaty for support.
