### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by FrenkT** [idiap/IBDiarization#9]
Hi,

I am running this diarization toolkit on a Xeon processor with 8 cores (and 16 threads). 
I edited the run.diarizeme.sh script so that $diarizeme_bin is called with --nthread 16, but when I run it, it looks like (from Top Command) only 1 thread is being used. 
Is this an expected behaviour? Or what can I do to solve this?
Thanks

**Comment by mrsrikanth** [comment]
Hello,

Apologies for the delayed response.

The threading is only for one particular stage in the entire
diarization process, namely  IB clustering.
The rest of the process is indeed single threaded.
This is perhaps why you will see only one process for majority of the time.
Please let me know if this is not the case.

Thank you,
Srikanth

**Comment by FrenkT** [comment]
Yes, now I noticed that after a while it starts working with multithreading. Thank you.
